// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH13-NS0jvosqJcC2AVPOZYTxMvOqy10M',
    appId: '1:992111898520:web:7d2f5051a5e646443285ed',
    messagingSenderId: '992111898520',
    projectId: 'application-25fae',
    authDomain: 'application-25fae.firebaseapp.com',
    storageBucket: 'application-25fae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRY-LsY5hfb2eqO1doDsBdu9OZidGpXaM',
    appId: '1:992111898520:android:168d5e20df84dda43285ed',
    messagingSenderId: '992111898520',
    projectId: 'application-25fae',
    storageBucket: 'application-25fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByukwTjHVv9r1LpOlPGXJ33iXJFkmK6E0',
    appId: '1:992111898520:ios:99e095fbd83fa1f13285ed',
    messagingSenderId: '992111898520',
    projectId: 'application-25fae',
    storageBucket: 'application-25fae.appspot.com',
    iosBundleId: 'com.example.activitiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByukwTjHVv9r1LpOlPGXJ33iXJFkmK6E0',
    appId: '1:992111898520:ios:08a1e8ffbbf8c11b3285ed',
    messagingSenderId: '992111898520',
    projectId: 'application-25fae',
    storageBucket: 'application-25fae.appspot.com',
    iosBundleId: 'com.example.activitiesApp.RunnerTests',
  );
}
